name: 'terragrunt:demo'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches:
    - master
    paths:
    - 'terraform/live/demo/**'
  pull_request:

jobs:
  terraform:
    name: 'terragrunt:demo'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: 'asdf:install'
      uses: asdf-vm/actions/install@v1.0.0

    - name: 'terraform:provider:kubectl'
      run: |
        mkdir -p ~/.terraform.d/plugins
        curl -Ls https://api.github.com/repos/gavinbunney/terraform-provider-kubectl/releases/latest | jq -r ".assets[] | select(.browser_download_url | contains(\"$(uname -s | tr A-Z a-z)\")) | select(.browser_download_url | contains(\"amd64\")) | .browser_download_url" | xargs -n 1 curl -Lo ~/.terraform.d/plugins/terraform-provider-kubectl
        chmod +x ~/.terraform.d/plugins/terraform-provider-kubectl

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: 'terragrunt:init:vpc'
      run: |
        pushd terraform/live/demo/eu-west-3/vpc
        terragrunt init
        popd

    - name: 'terragrunt:fmt:vpc'
      run: |
        pushd terraform/live/demo/eu-west-3/vpc
        terragrunt fmt -check
        popd

    - name: 'terragrunt:validate:vpc'
      run: |
        pushd terraform/live/demo/eu-west-3/vpc
        terragrunt validate
        popd

    - name: 'terragrunt:plan:vpc'
      run: |
        pushd terraform/live/demo/eu-west-3/vpc
        terragrunt validate
        popd

